### ISSUE TITLE
Copy Truncates Data

### ISSUE THREAD

**Issue by fdncred** [chcg/NPP_ExportPlugin#1]
I mapped my Ctrl-C to “Copy All Formats To Clipboard” method of the NppExport plugin. I’ve noticed that it always misses the last character.

Example - if I select this entire sentence below and hit Ctrl-C:
Now is the time for all good men

When I paste it I get
Now is the time for all good me

**Comment by fdncred** [comment]
I downloaded the source code and fixed it this way.

    TXTExporter::exportData()
    Before:
    int totalBytesNeeded = ed->csd->nrChars;
    After:
    int totalBytesNeeded = ed->csd->nrChars + 1;

    RTFExporter::exportData()
    Before:
    int totalBytesNeeded = 1; //zero terminator
    After:
    int totalBytesNeeded = 2; //zero terminator

    HTMLExporter exportData()
    Before:
    int totalBytesNeeded = 1; //zero terminator
    After:
    int totalBytesNeeded = 2; //zero terminator

**Comment by chcg** [comment]
@fdncred 
This is just a test project of mine to port to x64, the official maintainer according to 
http://docs.notepad-plus-plus.org/index.php/Plugin_Central#Npp
is harrybharry@users.sourceforge.net. I didn't contact him yet about his plans to update the project.

**Comment by fdncred** [comment]
Thanks @chcg.  Sorry, I didn't realize this wasn't "official". I'll try to email him but his code doesn't look like it's changed in 8 years.

**Comment by chcg** [comment]
@fdncred 
Yes, last release is quite old. Would be nice if you let me know if you have any news, about the maintance.
