### ISSUE TITLE
I want to use this plugin in C#

### ISSUE THREAD

**Issue by LittleNewton** [chcg/NPP_ExportPlugin#16]
I am developing a VSTO Office Add-In for MS Word.

The Code Highlighting is very hard for me to implementing. Could you please tell me some way to call this `nppexport.dll`  from C#?

I want to call this dll to add the HTML to my clipboard automatically.

Very Thanks.

**Comment by chcg** [comment]
@LittleNewton This dll can't be called standalone without N++. So you would need to access N++ from C# and I'm not aware of such an option.

**Comment by LittleNewton** [comment]
> @LittleNewton This dll can't be called standalone without N++. So you would need to access N++ from C# and I'm not aware of such an option.

Thank you very much.

I will try my best to do it.
