### ISSUE TITLE
Copy all formats, or copy Html, does not include <br> or &#32; so all is scrunched up.

### ISSUE THREAD

**Issue by mckuipers** [chcg/NPP_ExportPlugin#18]
Hi

When I copy from a tool like AquaDataStudio, and paste in a tapatalk [CODE] section it is colorised has spaces and line breaks.
When I copy using nppexport in tapatalk, the color stays but the spaces are gone and so are the line breaks.

A simple:
Select *
From Orders;

Copied from ADS into https://evercoder.github.io/clipboard-inspector/ I get:

```html
<html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body><pre style="background-color:#ffffff;color:#000000;font-family:'Courier New';font-size:9.0pt;"><span style="color:#0000ff;font-weight:bold;">Select&#32;</span>*<br><span style="color:#0000ff;font-weight:bold;">From&#32;</span>Orders;<br></pre></body></html>
```

Copied from nppExport I get

```html
<html>
<!--StartFragment-->
<head>
<META http-equiv=Content-Type content="text/html; charset=UTF-8">
<title>Exported from Notepad++</title>
<style type="text/css">
span {
	font-family: 'Courier New';
	font-size: 10pt;
	color: #000000;
}
.sc0 {
}
.sc5 {
	font-weight: bold;
	color: #0000FF;
}
.sc10 {
	font-weight: bold;
	color: #000080;
}
.sc11 {
}
</style>
</head>
<body>
<div style="float: left; white-space: pre; line-height: 1; background: #FFFFFF; "><span class="sc5">Select</span><span class="sc0"> </span><span class="sc10">*</span><span class="sc0">
</span><span class="sc5">From</span><span class="sc0"> </span><span class="sc11">Orders</span><span class="sc10">;</span></div><!--EndFragment-->
</body>
</html>
```

I would appreciate if this could be looked at.

Kind regards
Marco

**Comment by chcg** [comment]
@mckuipers If I watch the output in a browser (firefox, edge) it looks ok. From my understanding using the space directly or the encoded version #32; (https://www.w3.org/MarkUp/html-spec/html-spec_13.html) should make no difference. Similar for the CR LF (carriage return, linefeed) as used by windows.

The input for the test was issue18.sql with the text from above:
```sql
Select *
From Orders;
```

So maybe that is an issue with the tapatalk handling. Do you know if tapatalk is using direct html as input or markdown like github which allows to embed some elements of html?
