### ISSUE TITLE
VS2015 project file

### ISSUE THREAD

**Issue by donho** [chcg/NPP_ExportPlugin#2]
Nice effort! However, I don't see the VS2015 project file in the repository. Does it exist but not in repository or we have to convert it from VS2013 project file by using VS2015?

**Comment by chcg** [comment]
There is just the VS2013 config https://github.com/chcg/NPP_ExportPlugin/blob/master/vs7project/NppExport.vcxproj. VS2015 could load it and use it. The only change is regarding the toolversion (12.0 -> 14.0 )and PlatformToolset (v120_xp -> v140_xp).

In the appveyor build this is done via the msbuild parameter /p:PlatformToolset.

@donho Why is VS2015 vcxproj an issue?

**Comment by chcg** [comment]
@donho updated project file to VS2015, see https://github.com/chcg/NPP_ExportPlugin/commit/572e0cb2f5e64d2d43914b4a5787bfbead12da92
