### ISSUE TITLE
Feature request - Copy styled text

### ISSUE THREAD

**Issue by Gentleman-Jack** [chcg/NPP_ExportPlugin#20]
I have some text colored with styled formatting, I would like to be able to export this to a file and keep the colors. Screenshot attached

![image](https://user-images.githubusercontent.com/78911200/197534764-17f85414-1c97-423b-9e72-543093de1b75.png)

**Comment by Gentleman-Jack** [comment]
Tested on 8.6.4 x64, plugin version 0.4

**Comment by chcg** [comment]
Duplicate to #15
