### ISSUE TITLE
Translation of the plugin into Russian.

### ISSUE THREAD

**Issue by andrecool-68** [chcg/NPP_ExportPlugin#5]
In the HTMLExporter file.cpp

I changed the encoding from windows-1252 to UTF-8

```
	currentBufferOffset += sprintf(clipbuffer+currentBufferOffset, "<head>\r\n");

	currentBufferOffset += sprintf(clipbuffer+currentBufferOffset, "<META http-equiv=Content-Type content=\"text/html; charset=");
	if (ed->csd->currentCodePage == SC_CP_UTF8) {
		currentBufferOffset += sprintf(clipbuffer+currentBufferOffset, "UTF-8");
	} else {
		//currentBufferOffset += sprintf(clipbuffer+currentBufferOffset, "iso-8859-1");
		currentBufferOffset += sprintf(clipbuffer+currentBufferOffset, "UTF-8");
	}
```

All text strings were translated into Russian and all translated files had to change the encoding to utf-8+BOM, otherwise there was a problem with the Russian font. Wanted to know if I did the right thing?

![default](https://user-images.githubusercontent.com/3471892/52295213-e3c05c80-2983-11e9-8026-f6a1b0b081ae.png)

**Comment by andrecool-68** [comment]
The first time I did the translation in Notepad++ and built the project in VS 2015, and there were problems with the Russian font. Today I translated into Russian and collected the project in VS 2017, everything turned out well even did not change the encoding in the HTMLExporter file.cpp. This Notepad++ broke the encoding when translating and saving the file. Problem solved!

**Comment by chcg** [comment]
@andrecool-68 The input file needs to be encoded properly so the export is done with UTF8, otherwise https://en.wikipedia.org/wiki/ISO/IEC_8859-1 is used not containing cyrillic chars. Was that the problem you described? 
Could this be closed?

**Comment by andrecool-68** [comment]
@chcg  You probably do not understand me, I translated the resource files into Russian. After building the project there were problems with Cyrillic, the encoding in the resource files broke Notepad++ when saving the file. Now I am engaged in localization directly in Visual Studio. Problem solved!

**Comment by chcg** [comment]
@andrecool-68 So you found something similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5299, where the encoding was modified implicitly by N++ while saving the file.

**Comment by andrecool-68** [comment]
Notepad++ recently has a big problem with opening and saving files, a lot of errors with the encoding. The file with the Russian text can show the encoding of Vietnam or another. I translated the resource files of your plugin into Russian and saved them in utf-8 encoding (in Notepad++), after the build in VS2015 or VS2017 the Russian language in the plugin does not work correctly. BUT if everything is done in VS2015 or VS2017 the problems with the Russian language there!
Every year in Notepad++ there are a lot of problems, and the old problems are not corrected.  It all started when there was a Notepad++ version 6

**Comment by andrecool-68** [comment]
Here is an example of saving the encoding in Notepad++, actually I wanted to save in utf-8 encoding
![default](https://user-images.githubusercontent.com/3471892/52521738-597a4000-2c84-11e9-89ad-e7f29d35e032.png)

**Comment by chcg** [comment]
![grafik](https://user-images.githubusercontent.com/12630740/52590935-e23eda80-2e42-11e9-9f3b-ab269ad3d6d5.png)

you could switch off the "autodetect character encoding" to avoid this issue

**Comment by andrecool-68** [comment]
@chcg  I made a forced save in the desired encoding through the menu "encoding", and what you have shown here will not help at all.

**Comment by chcg** [comment]
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4925 and the revert https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5414 due to problems with the heuristic of charset detection.
